/*
 * Decompiled with CFR 0.152.
 */
/*
 * Illegal identifiers - consider using --renameillegalidents true
 */
public class aw {
    public static String a = "";
    public static String b = "";
    public static String c = "";
    public static String d = "";
    public static String e = "";
    public static String f = "";
    public static String g = "";
    public static String h = "";
    public static String i = "";
    public static String j = "";
    public static String k = "";
    public static String l;
    public static String m;
    public static String n;
    public static String o;
    public static String p;
    public static String q;
    public static String r;
    public static String s;
    public static String t;
    public static String u;
    public static String v;
    public static String w;
    public static String x;
    public static String y;
    public static String z;
    public static String A;
    public static String B;
    public static String C;
    public static String D;
    public static String E;
    public static String F;
    public static String G;
    public static String H;
    public static String I;
    public static String J;
    public static String K;
    public static String L;
    public static String M;
    public static String N;
    public static String O;
    public static String P;
    public static String Q;
    public static String R;
    public static String S;
    public static String T;
    public static String U;
    public static String V;
    public static String W;
    public static String X;
    public static String Y;
    public static String Z;
    public static String aa;
    public static String ab;
    public static String ac;
    public static String ad;
    public static String[] ae;
    public static String af;
    public static String ag;
    public static String ah;
    public static String ai;
    public static String aj;
    public static String ak;
    public static String al;
    public static String am;
    public static String an;
    public static String ao;
    public static String ap;
    public static String aq;
    public static String ar;
    public static String as;
    public static String at;
    public static String au;
    public static String av;
    public static String aw;
    public static String ax;
    public static String ay;
    public static String az;
    public static String aA;
    public static String aB;
    public static String aC;
    public static String aD;
    public static String aE;
    public static String aF;
    public static String aG;
    public static String aH;
    public static String aI;
    public static String[] aJ;
    public static String[] aK;
    public static String[] aL;
    public static String[][] aM;
    public static String[][] aN;
    public static String[][] aO;
    public static String[][] aP;
    public static String[] aQ;
    public static String[] aR;
    public static String aS;
    public static String aT;
    public static String aU;
    public static String[] aV;
    public static String[] aW;
    public static String[] aX;
    public static String aY;
    public static String aZ;
    public static String ba;
    public static String bb;
    public static String bc;
    public static String bd;
    public static String be;
    public static String bf;
    public static String bg;
    public static String bh;
    public static String bi;
    public static String bj;
    public static String bk;
    public static String bl;
    public static String bm;
    public static String bn;
    public static String bo;
    public static String bp;
    public static String bq;
    public static String br;
    public static String bs;
    public static String bt;
    public static String bu;
    public static String bv;
    public static String bw;
    public static String bx;
    public static String by;
    public static String bz;
    public static String bA;
    public static String bB;
    public static String bC;
    public static String bD;
    public static String bE;
    public static String bF;
    public static String bG;
    public static String bH;
    public static String bI;
    public static String bJ;
    public static String bK;
    public static String bL;
    public static String bM;
    public static String bN;
    public static String bO;
    public static String bP;
    public static String bQ;
    public static String bR;
    public static String bS;
    public static String bT;
    public static String bU;
    public static String bV;
    public static String bW;
    public static String bX;
    public static String bY;
    public static String bZ;
    public static String ca;
    public static String cb;
    public static String cc;
    public static String[] cd;
    public static String[] ce;
    public static String[] cf;
    public static String[] cg;
    public static String[] ch;
    public static String[] ci;
    public static String[] cj;
    public static String ck;
    public static String cl;
    public static String cm;
    public static String cn;
    public static String co;
    public static String cp;
    public static String cq;
    public static String cr;
    public static String cs;
    public static String ct;
    public static String cu;
    public static String cv;
    public static String cw;
    public static String cx;
    public static String cy;
    public static String cz;
    public static String cA;
    public static String cB;
    public static String cC;
    public static String cD;
    public static String cE;
    public static String cF;
    public static String cG;
    public static String cH;
    public static String cI;
    public static String cJ;
    public static String cK;
    public static String cL;
    public static String cM;
    public static String cN;
    public static String cO;
    public static String cP;
    public static String cQ;
    public static String cR;
    public static String cS;
    public static String cT;
    public static String cU;
    public static String cV;
    public static String cW;
    public static String cX;
    public static String cY;
    public static String cZ;
    public static String da;
    public static String db;
    public static String dc;
    public static String dd;
    public static String de;
    public static String[] df;
    public static String[] dg;
    public static String[] dh;
    public static String[] di;
    public static String[] dj;
    public static String[] dk;
    public static String[] dl;
    public static String[] dm;
    public static String dn;
    public static String do;
    public static String dp;
    public static String dq;
    public static String[] dr;
    public static String ds;
    public static String dt;
    public static String du;
    public static String dv;
    public static String dw;
    public static String dx;
    public static String dy;
    public static String dz;
    public static String dA;
    public static String dB;
    public static String dC;
    public static String dD;
    public static String dE;
    public static String dF;
    public static String dG;
    public static String dH;
    public static String dI;
    public static String dJ;
    public static String dK;
    public static String dL;
    public static String dM;
    public static String dN;
    public static String dO;
    public static String dP;
    public static String dQ;
    public static String dR;
    public static String dS;
    public static String dT;
    public static String dU;
    public static String dV;
    public static String dW;
    public static String dX;
    public static String dY;
    public static String dZ;
    public static String ea;
    public static String eb;
    public static String ec;
    public static String ed;
    public static String ee;
    public static String ef;
    public static String eg;
    public static String eh;
    public static String ei;
    public static String ej;
    public static String ek;
    public static String el;
    public static String em;
    public static String en;
    public static String eo;
    public static String ep;
    public static String eq;
    public static String er;
    public static String es;
    public static String et;
    public static String eu;
    public static String ev;
    public static String ew;
    public static String ex;
    public static String ey;
    public static String ez;
    public static String eA;
    public static String eB;
    public static String eC;
    public static String eD;
    public static String eE;
    public static String eF;
    public static String eG;
    public static String eH;
    public static String eI;
    public static String eJ;
    public static String eK;
    public static String eL;
    public static String eM;
    public static String eN;
    public static String eO;
    public static String eP;
    public static String eQ;
    public static String eR;
    public static String eS;
    public static String eT;
    public static String eU;
    public static String eV;
    public static String eW;
    public static String eX;
    public static String eY;
    public static String eZ;
    public static String fa;
    public static String fb;
    public static String fc;
    public static String fd;
    public static String fe;
    public static String ff;
    public static String fg;
    public static String fh;
    public static String fi;
    public static String fj;
    public static String fk;
    public static String fl;
    public static String[][] fm;
    public static String fn;
    public static String fo;
    public static String fp;
    public static String fq;
    public static String fr;
    public static String fs;
    public static String ft;
    public static String fu;
    public static String fv;
    public static String fw;
    public static String fx;
    public static byte fy;
    public static String fz;
    public static String fA;
    public static String fB;
    public static String fC;
    public static String fD;
    public static String fE;
    public static String fF;
    public static String fG;
    public static String fH;
    public static String fI;
    public static String fJ;
    public static String fK;
    public static String fL;
    public static String fM;
    public static String fN;
    public static String fO;
    public static String fP;
    public static String fQ;
    public static String fR;
    public static String fS;
    public static String fT;
    public static String fU;
    public static String fV;
    public static String fW;
    public static String fX;
    public static String fY;
    public static String fZ;
    public static String ga;
    public static String gb;
    public static String gc;
    public static String gd;
    public static String ge;
    public static String gf;
    public static String gg;
    public static String gh;
    public static String gi;
    public static String gj;
    public static String gk;
    public static String gl;

    static {
        C = "";
        H = "";
        I = "";
        J = "";
        K = "";
        L = "";
        M = "";
        N = "";
        O = "";
        P = "";
        Q = "";
        R = "";
        S = "";
        T = "";
        U = "";
        V = "";
        W = "";
        X = "";
        Y = "";
        Z = "";
        aa = "";
        ab = "";
        ac = "";
        String[] stringArray = new String[]{"", ""};
        ad = "";
        ae = new String[]{"", ""};
        af = "";
        ag = "";
        ah = "";
        ai = "";
        aj = "";
        ak = "";
        al = "";
        am = "";
        an = "";
        ao = "";
        ap = "";
        aq = "";
        ar = "";
        as = "";
        at = "";
        au = "";
        av = "";
        aw = "";
        ax = "";
        ay = "";
        az = "";
        aA = "";
        aB = "";
        aC = "";
        aD = "";
        aE = "";
        aF = "";
        aG = "";
        aH = "";
        aI = "";
        String[] stringArray2 = new String[]{"", "", "", "", ""};
        aJ = new String[]{"", "", ""};
        aK = new String[]{"", "", ""};
        aL = new String[]{"", "", "", "", "", "", "", "", "", ""};
        aM = new String[][]{{"", ""}, {"", ""}, {"", ""}, {"", ""}};
        aN = new String[][]{{"", ""}, {"", ""}, {"", ""}, {"", ""}, {"", ""}};
        aO = new String[][]{{"", ""}, {"", ""}};
        aP = new String[][]{{"", ""}};
        aQ = new String[]{"", "", "", "", "", "", "", "", "", ""};
        aR = new String[]{"", "", "", "", "", "", "", "", "", ""};
        aS = "";
        aT = "";
        aU = "";
        aV = new String[]{" ", "", "", ""};
        aW = new String[]{"", "", "", ""};
        String[] stringArray3 = new String[]{"", "", ""};
        aX = new String[]{"", "", "", "", "", "", "", "", "", "", "", ""};
        aY = "";
        aZ = "";
        ba = "";
        bb = "";
        bc = "";
        bd = "";
        be = "";
        bf = "";
        bg = "";
        bh = "";
        bi = "";
        bj = "";
        bk = "";
        bl = "";
        bm = "";
        bn = "";
        bo = "";
        bp = "";
        bq = "";
        br = "";
        bs = "";
        bt = "";
        bu = "";
        bv = "";
        bw = "";
        bx = "";
        by = "";
        bz = "";
        bA = "";
        bB = "";
        bC = "";
        bD = "";
        bE = "";
        bF = "";
        bG = "";
        bH = "";
        bI = "";
        bJ = "";
        bK = "";
        bL = "";
        bM = "";
        bN = "";
        bO = "";
        bP = "";
        bQ = "";
        bR = "";
        bS = "";
        bT = "";
        bU = "";
        bV = "";
        bW = "";
        bX = "";
        bY = "";
        bZ = "";
        ca = "";
        cb = "";
        cc = "";
        cd = new String[]{"", ""};
        ce = new String[]{"", ""};
        cf = new String[]{"", ""};
        cg = new String[]{"", ""};
        ch = new String[]{"", ""};
        ci = new String[]{"", ""};
        cj = new String[]{"", ""};
        ck = "";
        cl = "";
        cm = "";
        cn = "";
        co = "";
        cp = "";
        cq = "";
        cr = "";
        cs = "";
        ct = "";
        cu = "";
        cv = "";
        cw = "";
        cx = "";
        cy = "";
        cz = "";
        cA = "";
        cB = "";
        cC = "";
        cD = "";
        cE = "";
        cF = "";
        cG = "";
        cH = "";
        cI = "";
        cJ = "";
        cK = "";
        cL = "";
        cM = "";
        cN = "";
        cO = "";
        cP = "";
        cQ = "";
        cR = "";
        cS = "";
        cT = "";
        cU = "";
        cV = "";
        cW = "";
        cX = "";
        cY = "";
        cZ = "";
        da = "";
        db = "";
        dc = "";
        dd = "";
        de = "";
        df = new String[]{"", ""};
        dg = new String[]{"", ""};
        dh = new String[]{"", ""};
        di = new String[]{"", ""};
        dj = new String[]{"", ""};
        dk = new String[]{""};
        dl = new String[]{""};
        dm = new String[]{"", ""};
        dn = "";
        do = "";
        dp = "";
        dq = "";
        dr = new String[]{"", "", "", "", ""};
        ds = "";
        dt = "";
        du = "";
        dv = "";
        dw = "";
        dx = "";
        dy = "";
        dz = "";
        dA = "";
        dB = "";
        dC = "";
        dD = "";
        dE = "";
        dF = "";
        dG = "";
        dH = "";
        dI = "";
        dJ = "";
        dK = "";
        dL = "";
        dM = "";
        dN = "";
        dO = "";
        dP = "";
        dQ = "";
        dR = "";
        dS = "";
        dT = "";
        dU = "";
        dV = "";
        dW = "";
        dX = "";
        dY = "";
        dZ = "";
        ea = "";
        eb = "";
        ec = "";
        ed = "";
        ee = "";
        ef = "";
        eg = "";
        eh = "";
        ei = "";
        ej = "";
        ek = "";
        el = "";
        em = "";
        en = "";
        eo = "";
        ep = "";
        eq = "";
        er = "";
        es = "";
        et = "";
        eu = "";
        ev = "";
        ew = "";
        ex = "";
        ey = "";
        ez = "";
        eA = "";
        eB = "";
        eC = "";
        eD = "";
        eE = "";
        eF = "";
        eG = "";
        eH = "";
        eI = "";
        eJ = "";
        eK = "";
        eL = "";
        eM = "";
        eN = "";
        eO = "";
        eP = "";
        eQ = "";
        eR = "";
        eS = "";
        eT = "";
        eU = "";
        eV = "";
        eW = "";
        eX = "";
        eY = "";
        eZ = "";
        fa = "";
        fb = "";
        fc = "";
        fd = "";
        fe = "";
        ff = "";
        fg = "";
        fh = "";
        fi = "";
        fj = "";
        fk = "";
        fl = "";
        fm = new String[][]{{"", "", ""}, {"", "", ""}, {"", "", ""}};
        fn = "";
        fo = "";
        fp = "";
        fq = "";
        fr = "";
        fs = "";
        ft = "";
        fu = "";
        fv = "";
        fw = "";
        fx = "";
        fB = "";
        fW = "";
        gh = "";
        gl = "";
        aw.a((byte)1);
    }

    public static void a(byte by) {
        fy = by;
        switch (fy) {
            case 0: {
                bs.l = "http://ngocrongonline.com";
                x.j = l.b("/mainImage/logo1.png");
                a = "T\u1edbi Whis (H\u00e0nh tinh Bill) \u0111\u1ec3 h\u1ecdc tuy\u1ec7t k\u1ef9";
                b = "Khi \u0111\u1ea1t t\u1ed1i \u0111a th\u00e0nh th\u1ea1o, h\u00e3y \u0111\u1ebfn Whis (H\u00e0nh tinh Bill) \u0111\u1ec3 n\u00e2ng c\u1ea5p tuy\u1ec7t k\u1ef9";
                c = "Th\u00e0nh th\u1ea1o";
                d = "X\u00f3a t\u00e0i kho\u1ea3n";
                e = "H\u00f4m nay b\u1ea1n \u0111\u00e3 n\u1ea1p nhi\u1ec1u ng\u1ecdc. Ng\u00e0y mai h\u00e3y n\u1ea1p ti\u1ebfp nh\u00e9!";
                f = "Khi b\u00e1n th\u00e0nh c\u00f4ng s\u1ebd nh\u1eadn l\u1ea1i H\u1ed3ng Ng\u1ecdc kh\u00f4ng ph\u1ea3i Ng\u1ecdc, b\u1ea1n c\u00f3 mu\u1ed1n ti\u1ebfp t\u1ee5c k\u00ed g\u1eedi?";
                g = "S\u1eed d\u1ee5ng";
                h = "M\u1edf kh\u00f3a";
                i = "S\u1ed5 s\u01b0u t\u1ea7m";
                j = "B\u1ea1n kh\u00f4ng \u0111\u1ee7";
                k = "Ch\u1ee9c n\u0103ng t\u1ea1m d\u1eebng \u0111\u1ec3 b\u1ea3o tr\u00ec";
                C = "N\u1ea1p Ng\u1ecdc";
                az = "B\u1ea1n c\u00f3 ch\u1eafc mu\u1ed1n nh\u1eb7t v\u1eadt ph\u1ea9m n\u00e0y kh\u00f4ng ?";
                l = "t\u1ea7ng";
                m = "Con s\u1ed1 may m\u1eafn";
                bS = "Mini game";
                bR = "Th\u00f4ng b\u00e1o";
                n = "T\u1ef1 \u0111\u1ed9ng h\u1ed3i sinh";
                o = "Ch\u1ee9c n\u0103ng auto";
                p = "B\u1ea1n c\u00f3 ch\u1eafc mu\u1ed1n k\u1ebft h\u1ee3p v\u0129nh vi\u1ec5n v\u1edbi \u0111\u1ec7 t\u1eed c\u1ee7a m\u00ecnh kh\u00f4ng? B\u1ea1n s\u1ebd m\u1ea5t \u0111\u1ec7 t\u1eed v\u00e0 to\u00e0n b\u1ed9 trang b\u1ecb \u0111\u1ec7 t\u1eed \u0111ang m\u1eb7c, to\u00e0n b\u1ed9 s\u1ee9c m\u1ea1nh c\u1ee7a \u0111\u1ec7 t\u1eed s\u1ebd chuy\u1ec3n th\u00e0nh ti\u1ec1m n\u0103ng c\u1ee7a b\u1ea1n";
                gj = "H\u1ee3p th\u1ec3 v\u0129nh vi\u1ec5n";
                gi = "H\u1ee3p th\u1ec3";
                gg = "Vui l\u00f2ng nh\u1eadp \u0111\u00fang s\u1ed1 l\u01b0\u1ee3ng cho ph\u00e9p";
                q = "Ch\u01a1i ti\u1ebfp";
                v = "V\u1ec1 nh\u00e0";
                u = "Tr\u1ea1ng th\u00e1i";
                r = "T\u1ea5n c\u00f4ng";
                s = "B\u1ea3o v\u1ec7";
                t = "\u0110i theo";
                w = "\u0110\u1ec7 t\u1eed";
                x = "M\u00e1y ch\u1ee7 t\u1eaft ho\u1eb7c m\u1ea5t s\u00f3ng";
                y = "C\u1ea5u h\u00ecnh th\u1ea5p";
                z = "C\u1ea5u h\u00ecnh cao";
                gb = "T\u1ea3i d\u1eef li\u1ec7u";
                gc = "X\u00f3a d\u1eef li\u1ec7u";
                gd = "B\u1ea1n c\u1ea7n x\u00f3a trong tr\u01b0\u1eddng h\u1ee3p c\u00f3 l\u1ed7i t\u1ea3i d\u1eef li\u1ec7u. Khi x\u00f3a xong, b\u1ea1n ph\u1ea3i t\u1ea3i l\u1ea1i to\u00e0n b\u1ed9 \u0111\u1ec3 c\u00f3 th\u1ec3 ch\u01a1i.";
                ga = "H\u1ee7y";
                fZ = "Vui l\u00f2ng t\u1ea3i d\u1eef li\u1ec7u \u0111\u1ec3 ch\u01a1i";
                A = "\u00dam ba la x\u00ec b\u00f9a...";
                D = "Ch\u00fac m\u1eebng con nh\u00e9";
                B = "Ch\u00fac con may m\u1eafn l\u1ea7n sau";
                fY = "B\u1ea1n c\u00f3 \u0111\u1ebfn t\u01b0\u01a1ng lai ngay b\u00e2y gi\u1edd v\u1edbi gi\u00e1 1 ng\u1ecdc kh\u00f4ng ?";
                fX = "T\u0103ng t\u1ed1c";
                E = "B\u00e0n ph\u00edm \u1ea3o";
                F = "B\u00e0n ph\u00edm \u1ea3o";
                G = "B\u00e0n ph\u00edm \u1ea3o";
                fU = "M\u00e3 b\u1ea3o v\u1ec7";
                fV = "Nh\u1eadp m\u00e3 b\u1ea3o v\u1ec7";
                fW = "M\u00e3 b\u1ea3o v\u1ec7 ph\u1ea3i c\u00f3 \u0111\u1ed9 d\u00e0i l\u00e0 6 s\u1ed1.";
                fT = "Vui l\u00f2ng nh\u1eadp s\u1ed1 \u0111i\u1ec7n tho\u1ea1i ho\u1eb7c \u0111\u1ecba ch\u1ec9 email,sau \u0111\u00f3 nh\u1eadp m\u1eadt kh\u1ea9u \u0111\u1ec3 t\u1ea1o t\u00e0i kho\u1ea3n m\u1edbi";
                fS = "B\u1ea1n s\u1ebd m\u1ea5t t\u00e0i kho\u1ea3n \u0111ang ch\u01a1i v\u00e0 kh\u00f4ng th\u1ec3 kh\u00f4i ph\u1ee5c \u0111\u01b0\u1ee3c n\u1ebfu \u0111\u1ed5i t\u00e0i kho\u1ea3n kh\u00e1c, b\u1ea1n c\u00f3 \u0111\u1ed3ng \u00fd kh\u00f4ng ?";
                H = "\u0110\u0103ng k\u00ed \u0111\u1ec3 b\u1ea3o v\u1ec7 t\u00e0i kho\u1ea3n";
                fR = "B\u1ea1n ph\u1ea3i ho\u00e0n th\u00e0nh nhi\u1ec7m v\u1ee5 t\u00ecm ng\u1ecdc 6 sao m\u1edbi c\u00f3 th\u1ec3 n\u1ea1p ti\u1ec1n";
                fQ = "Di\u1ec5n \u0111\u00e0n v\u00e0 N\u1ea1p Ng\u1ecdc";
                fP = "Ch\u01b0a c\u00f3 v\u1eadt ph\u1ea9m rao b\u00e1n";
                fO = "K\u00e9o l\u00ean \u0111\u1ec3 c\u1eadp nh\u1eadt th\u00eam";
                fN = "K\u00e9o xu\u1ed1ng \u0111\u1ec3 c\u1eadp nh\u1eadt th\u00eam";
                fM = "Trang";
                fL = "Up Top";
                fD = "B\u00e1n b\u1eb1ng\nv\u00e0ng";
                fE = "B\u00e1n b\u1eb1ng\nng\u1ecdc";
                fF = "B\u00e1n b\u1eb1ng v\u00e0ng";
                fG = "B\u00e1n b\u1eb1ng ng\u1ecdc";
                fH = "H\u1ee7y\nk\u00ed g\u1eedi";
                fI = "Nh\u1eadn ti\u1ec1n";
                fK = "\u0110\u00e3 b\u00e1n";
                fJ = "\u0110ang b\u00e1n";
                fC = "K\u00ed g\u1eedi";
                fz = "\u00c2m thanh";
                fA = "\u00c2m thanh";
                bK = "H\u1ea1ng";
                aa = "Ch\u1ecdn m\u00e1y ch\u1ee7";
                bL = "N\u0103ng \u0111\u1ed9ng";
                I = "\u0110ang \u0111\u0103ng k\u00fd";
                J = "\u0110\u00e3 g\u1eedi tin nh\u1eafn, xin ch\u1edd tin nh\u1eafn x\u00e1c nh\u1eadn.";
                K = "Kh\u00f4ng th\u1ec3 g\u1edfi tin nh\u1eafn. Xin ki\u1ec3m tra ti\u1ec1n v\u00e0 th\u1eed kh\u1edfi \u0111\u1ed9ng l\u1ea1i game.";
                L = "G\u1eedi tin nh\u1eafn th\u00e0nh c\u00f4ng";
                M = "Kh\u00f4ng th\u1ec3 g\u1eedi tin nh\u1eafn";
                N = "Ch\u00fac m\u1eebng b\u1ea1n \u0111\u00e3 g\u1edfi tin nh\u1eafn d\u1ef1 \u0111o\u00e1n th\u00e0nh c\u00f4ng.";
                O = "Tin nh\u1eafn g\u1eedi kh\u00f4ng th\u00e0nh c\u00f4ng.";
                P = "M\u1eadt kh\u1ea9u ph\u1ea3i c\u00f3 \u0111\u1ed9 d\u00e0i l\u00e0 6 k\u00fd t\u1ef1.";
                Q = "M\u1eadt kh\u1ea9u b\u1ea3o v\u1ec7 ch\u1ec9 cho nh\u1eadp s\u1ed1.";
                R = "Nh\u1eadp m\u1eadt kh\u1ea9u b\u1ea3o v\u1ec7";
                S = "\u0110\u1ed5i t\u00e0i kho\u1ea3n";
                T = "B\u1ea1n ch\u01b0a nh\u1eadp email ho\u1eb7c s\u1ed1 di \u0111\u1ed9ng.";
                U = "B\u1ea1n ch\u01b0a nh\u1eadp m\u1eadt kh\u1ea9u";
                V = "T\u00ean t\u00e0i kho\u1ea3n ph\u1ea3i nhi\u1ec1u h\u01a1n 5 k\u00fd t\u1ef1";
                W = "S\u1ed1 di \u0111\u1ed9ng kh\u00f4ng h\u1ee3p l\u1ec7. Xin nh\u1eadp theo m\u1eabu 0912345678 ho\u1eb7c 84918765432";
                X = "Email kh\u00f4ng h\u1ee3p l\u1ec7. Xin nh\u1eadp theo m\u1eabu tencuaban@yahoo.com ho\u1eb7c tencuaban@gmail.com";
                Y = "\u0110\u0103ng k\u00fd\nt\u00e0i kho\u1ea3n\nm\u1edbi";
                Z = "Ch\u1ecdn\nm\u00e1y ch\u1ee7";
                ab = "Qu\u00ean M.kh\u1ea7u";
                ac = "M\u1eadt kh\u1ea9u";
                String[] stringArray = new String[]{"Ch\u01b0a c\u00f3 t\u00e0i kho\u1ea3n xin", "ch\u1ecdn menu \u0111\u0103ng k\u00fd."};
                ad = "Tin nh\u1eafn";
                ae = new String[]{"Tin", "nh\u1eafn"};
                af = "Kh\u00f4ng c\u00f3 tin nh\u1eafn";
                ag = "B\u1ea1n c\u00f3 mu\u1ed1n hu\u1ef7 ch\u1ee9c n\u0103ng b\u1ea3o v\u1ec7 t\u00e0i kho\u1ea3n kh\u00f4ng ?";
                ah = "Ki\u1ec3m tra ch\u00ednh x\u00e1c \u0111\u1ec3 l\u1ea5y l\u1ea1i \u0111\u01b0\u1ee3c t\u00e0i kho\u1ea3n n\u1ebfu sau n\u00e0y qu\u00ean m\u1eadt kh\u1ea9u\n";
                ai = "S\u1ed1 di \u0111\u1ed9ng";
                aj = "\u0110\u1ecba ch\u1ec9 mail";
                ak = "TK";
                al = "MK";
                am = "\u0110\u1ec3 l\u1ea5y l\u1ea1i m\u1eadt kh\u1ea9u, xin vui l\u00f2ng v\u00e0o website http://ngocrongonline.com/matkhau";
                an = "Ng\u1ecdc r\u1ed3ng";
                ao = "Nh\u00e2n v\u1eadt";
                ap = "T\u00e0i kho\u1ea3n";
                aq = "M\u00e1y ch\u1ee7";
                ar = "B\u1ea1n ch\u01b0a nh\u1eadp t\u00ean nh\u00e2n v\u1eadt";
                as = "T\u00ean nh\u00e2n v\u1eadt qu\u00e1 ng\u1eafn";
                at = "T\u00ean nh\u00e2n v\u1eadt kh\u00f4ng \u0111\u01b0\u1ee3c qu\u00e1 15 k\u00ed t\u1ef1";
                au = "Nh\u00e2n v\u1eadt c\u1ea7n \u0111\u1ed5i t\u00ean";
                av = "T\u00ean nh\u00e2n v\u1eadt";
                aw = "\u0110\u0103ng nh\u1eadp";
                ax = "\u0110.Nh\u1eadp";
                ay = "\u0110\u0103ng k\u00fd";
                gk = "D\u1ecbch \nchuy\u1ec3n t\u1edbi";
                bq = "Tr\u1ea3 th\u00f9";
                aA = "Ch\u1edd";
                aB = "Xin ch\u1edd";
                aC = "\u0110ang k\u1ebft n\u1ed1i";
                fB = "Kh\u00f4ng c\u00f3 k\u1ebb th\u00f9";
                aD = "\u0110ang t\u1ea3i ";
                aE = "C\u00f3 l\u1ed7i x\u1ea3y ra, xin vui l\u00f2ng kh\u1edfi \u0111\u1ed9ng l\u1ea1i game.";
                aF = "\u0110\u1ed5i khu v\u1ef1c";
                aG = "Ch\u1ecdn khu v\u1ef1c";
                aH = "Website\ndi\u1ec5n \u0111\u00e0n";
                aI = "M\u00e1y ch\u1ee7";
                String[] stringArray2 = new String[]{"H\u00e0nh trang", "K\u1ef9 n\u0103ng", "Ti\u1ec1m n\u0103ng", "Th\u00f4ng tin", "Trang b\u1ecb"};
                aJ = new String[]{"", "D\u00e2n t\u1ed9c: ", "T\u00f3c: "};
                aK = new String[]{"Tr\u00e1i \u0111\u1ea5t", "Nam\u1ebfc", "Xayda"};
                if (l.c == 7) {
                    aK = new String[]{"R\u1ed3ng \u0111\u1ea5t", "R\u1ed3ng xanh", "R\u1ed3ng \u0111\u1ecf"};
                }
                aL = new String[]{"Th\u00e1ch \u0111\u1ea5u", "Luy\u1ec7n t\u1eadp", "C\u1eebu s\u00e1t", "K\u1ebft b\u1ea1n", "M\u1eddi v\u00e0o bang", "Ph\u1ee5c h\u1ed3i", "Xem th\u00f4ng tin", "Chat ri\u00eang", "M\u1eddi v\u00e0o t\u1ed9c", "Ch\u1eb7n xin v\u00e0o t\u1ed9c"};
                aM = new String[][]{{"Nhi\u1ec7m", "V\u1ee5"}, {"H\u00e0nh", "Trang"}, {"K\u1ef9", "N\u0103ng"}, {"Ch\u1ee9c", "N\u0103ng"}};
                aN = new String[][]{{"Nhi\u1ec7m", "V\u1ee5"}, {"H\u00e0nh", "Trang"}, {"K\u1ef9", "N\u0103ng"}, {"Bang", "H\u1ed9i"}, {"Ch\u1ee9c", "N\u0103ng"}};
                aO = new String[][]{{"\u0110\u1ec7", "T\u1eed"}, {"Tr\u1ea1ng", "Th\u00e1i"}, {"H\u00e0nh", "Trang"}};
                aP = new String[][]{{"\u0110\u1ec7", "T\u1eed"}, {"Tr\u1ea1ng", "Th\u00e1i"}};
                aQ = new String[]{"V\u00e0o\nph\u00edm Q", "V\u00e0o\nph\u00edm W", "V\u00e0o\nph\u00edm E", "V\u00e0o\nph\u00edm R", "V\u00e0o\nph\u00edm T", "", "", "", "", ""};
                aR = new String[]{"V\u00e0o\nph\u00edm 7", "V\u00e0o\nph\u00edm 8", "V\u00e0o\nph\u00edm 9", "V\u00e0o\nph\u00edm 1", "V\u00e0o\nph\u00edm 3", "", "", "", "", ""};
                aS = "Chi\u00eau \u0111\u00e1nh hi\u1ec7n t\u1ea1i c\u1ee7a b\u1ea1n ch\u01b0a n\u00e2ng c\u1ea5p \u0111\u1ed9";
                aT = "\u0110\u00e3 h\u1ebft \u0111\u1eadu th\u1ea7n. C\u1eadu h\u00e3y v\u1ec1 thu ho\u1ea1ch th\u00eam";
                aU = "B\u1ea1n \u0111ang \u1edf khu v\u1ef1c n\u00e0y";
                aV = new String[]{"H\u00e3y \u0111i t\u00ecm ", " \u1edf ", " \u0111\u1ec3 nh\u1eadn nhi\u1ec7m v\u1ee5.", "B\u1ea1n \u0111\u00e3 ho\u00e0n th\u00e0nh h\u1ebft nhi\u1ec7m v\u1ee5 phi\u00ean b\u1ea3n n\u00e0y, vui l\u00f2ng ch\u1edd cho \u0111\u1ebfn khi ra phi\u00ean b\u1ea3n ti\u1ebfp theo."};
                aW = new String[]{"Ki\u1ec7t s\u1ee9c", "Ch\u1edd", "V\u1ec1 nh\u00e0", "H\u1ed3i sinh\nngay\n(1 ng\u1ecdc)"};
                String[] stringArray3 = new String[]{"B\u1ea3n \u0111\u1ed3", "Nhi\u1ec7m v\u1ee5", "Gia t\u1ed9c"};
                aX = new String[]{"\u0110\u1eadu th\u1ea7n d\u00f9ng \u0111\u1ec3 t\u0103ng KI v\u00e0 HP ngay l\u1eadp t\u1ee9c", "B\u1ea1n ch\u1ec9 mang theo ng\u01b0\u1eddi \u0111\u01b0\u1ee3c 10 h\u1ea1t \u0111\u1eadu. N\u1ebfu mu\u1ed1n mang nhi\u1ec1u h\u01a1n, h\u00e3y xin t\u1eeb b\u1ea1n b\u00e8 trong Bang", "T\u1ea5t c\u1ea3 c\u00e1c s\u00e1ch k\u1ef9 n\u0103ng \u0111\u1ec1u c\u00f3 th\u1ec3 h\u1ecdc mi\u1ec5n ph\u00ed t\u1ea1i Quy L\u00e3o Kame, khi b\u1ea1n c\u00f3 \u0111\u1ee7 \u0111i\u1ec3m ti\u1ec1m n\u0103ng", "B\u1ea1n kh\u00f4ng th\u1ec3 bay, d\u00f9ng k\u1ef9 n\u0103ng, n\u1ebfu h\u1ebft KI", "T\u1ea5n c\u00f4ng qu\u00e1i v\u1eadt c\u00f9ng b\u1ea1n b\u00e8 trong Bang s\u1ebd mang l\u1ea1i nhi\u1ec1u \u0111i\u1ec3m ti\u1ec1m n\u0103ng h\u01a1n \u0111\u00e1nh m\u1ed9t m\u00ecnh", "T\u1eadp luy\u1ec7n v\u1edbi b\u1ea1n b\u00e8 t\u1ea1i khu v\u1ef1c th\u00edch h\u1ee3p s\u1ebd mang l\u1ea1i nhi\u1ec1u \u0111i\u1ec3m ti\u1ec1m n\u0103ng h\u01a1n \u0111\u00e1nh qu\u00e1i v\u1eadt", "Khi \u0111\u01b0\u1ee3c n\u00e2ng c\u1ea5p, \u0111\u1eadu th\u1ea7n s\u1ebd ph\u1ee5c h\u1ed3i nhi\u1ec1u HP v\u00e0 KI h\u01a1n", "V\u00e0o tr\u00f2 ch\u01a1i \u0111\u1ec1u \u0111\u1eb7n m\u1ed7i ng\u00e0y \u0111\u1ec3 nh\u1eadn \u0111\u01b0\u1ee3c Ng\u1ecdc mi\u1ec5n ph\u00ed", "\u0110\u00f9i g\u00e0 s\u1ebd ph\u1ee5c h\u1ed3i 100% HP, KI. C\u00e0 chua ph\u1ee5c h\u1ed3i 100% KI. C\u00e0 r\u1ed1t ph\u1ee5c h\u1ed3i 100% HP", "C\u00e2y \u0111\u1eadu th\u1ea7n k\u1ebft m\u1ed9t h\u1ea1t sau m\u1ed9t th\u1eddi gian, cho d\u00f9 b\u1ea1n \u0111ang offline", "Sau 3 ng\u00e0y kh\u00f4ng tham gia tr\u00f2 ch\u01a1i, b\u1ea1n s\u1ebd b\u1ecb gi\u1ea3m s\u1ee9c m\u1ea1nh do l\u01b0\u1eddi luy\u1ec7n t\u1eadp", "B\u1ea1n s\u1ebd gi\u1ea3m th\u1ec3 l\u1ef1c khi \u0111\u00e1nh qu\u00e1i, nh\u01b0ng s\u1ebd t\u0103ng l\u1ea1i th\u1ec3 l\u1ef1c khi kh\u00f4ng \u0111\u00e1nh n\u1eefa", "Khi n\u00e0o h\u1ebft ng\u1ecdc, b\u1ea1n h\u00e3y \u0111\u1ebfn ch\u1ed7 B\u00f2 M\u1ed9ng"};
                aY = "Sau khi gia nh\u1eadp v\u00e0o l\u1edbp h\u1ecdc, th\u00ec c\u00f3 th\u1ec3 nh\u1eadn nhi\u1ec7m v\u1ee5 t\u1eeb hi\u1ec7u tr\u01b0\u1edfng";
                aZ = "S\u1ed1 seri";
                ba = "M\u00e3 th\u1ebb";
                bb = "N\u1ea1p th\u1ebb Vina, Mobi, Viettel, Gate";
                bc = "N\u1ea1p th\u1ebb";
                bd = "Vui l\u00f2ng nh\u1eadp s\u1ed1 serial";
                be = "Vui l\u00f2ng nh\u1eadp m\u00e3 code";
                bf = "T\u1ec9";
                bg = "Tr";
                bh = "Menu";
                bi = "\u0110\u00f3ng";
                bj = "X\u00f3a";
                bk = "Ti\u1ebfp t\u1ee5c";
                bl = "S\u1eed d\u1ee5ng";
                bm = "C\u00f3";
                bn = "Kh\u00f4ng";
                bo = "Tho\u00e1t";
                bp = "Chat";
                br = "OK";
                bs = "Nh\u1edb";
                bt = "\u0110\u1ed3ng \u00fd";
                bu = "H\u1ee7y";
                bv = "Ch\u1ecdn";
                bw = "\u0110i v\u00e0o";
                bx = "M\u1edf link";
                aw.by = "T\u1ea1o m\u1edbi";
                bz = "\u0110\u00f3ng";
                bA = "Ti\u00eau di\u1ec7t";
                bB = "B\u1eaft t\u00e0 th\u00fa";
                bC = "v\u00e0ng";
                bD = "ng\u1ecdc";
                bE = "h\u1ed3ng ng\u1ecdc";
                bF = "\u0110i\u1ec3m hi\u1ebfu chi\u1ebfn c\u1ee7a b\u1ea1n hi\u1ec7n t\u1ea1i l\u00e0 ";
                bG = " b\u1eaft \u0111\u1ea7u c\u1eebu s\u00e1t b\u1ea1n";
                bH = "Kh\u00f4ng \u0111\u1ee7 KI \u0111\u1ec3 s\u1eed d\u1ee5ng";
                bI = "B\u1ea1n nh\u1eadn \u0111\u01b0\u1ee3c";
                bJ = "B\u1ea1n h\u1ecdc \u0111\u01b0\u1ee3c ";
                bM = "B\u1ea1n b\u00e8";
                bN = "K\u1ebb th\u00f9";
                bO = "Kh\u00f4ng c\u00f3 b\u1ea1n b\u00e8";
                bP = "Chat th\u1ebf gi\u1edbi";
                bQ = "\u0110\u1ed5i c\u1edd";
                bT = "C\u1ea5u h\u00ecnh";
                bU = "T\u0103ng \u0111\u1ed3 h\u1ecda (cho m\u00e1y m\u1ea1nh)";
                bV = "Gi\u1ea3m \u0111\u1ed3 h\u1ecda (cho m\u00e1y y\u1ebfu)";
                bW = "Th\u00f4ng b\u00e1o t\u1eeb m\u00e1y ch\u1ee7";
                ca = "H\u00e0o quang \u0111\u1eb7c bi\u1ec7t";
                cb = "H\u00e0o quang s\u1ee9c m\u1ea1nh";
                bX = "M\u00e0n h\u00ecnh l\u1edbn";
                bY = "M\u00e0n h\u00ecnh nh\u1ecf";
                bZ = "B\u1ea1n c\u00f3 mu\u1ed1n tho\u00e1t game \u0111\u1ec3 thay \u0111\u1ed5i c\u1ee1 m\u00e0n h\u00ecnh kh\u00f4ng ?";
                cc = "R\u01b0\u01a1ng \u0111\u1ed3";
                cd = new String[]{"R\u01b0\u01a1ng", "\u0110\u1ed3"};
                ce = new String[]{"H\u00e0nh", "Trang"};
                cf = new String[]{"K\u1ebft", "h\u1ee3p"};
                cg = new String[]{"B\u1ea3n", "\u0111\u1ed3"};
                ch = new String[]{"Item", "cho"};
                ci = new String[]{"Item", "nh\u1eadn"};
                cj = new String[]{"Khu", "V\u1ef1c"};
                ck = "Khu v\u1ef1c";
                cl = "B\u1ea3n \u0111\u1ed3";
                cm = "Item nh\u1eadn";
                cn = "Nh\u1eadn";
                co = "Nh\u1eadn t\u1ea5t";
                cp = "H\u00e3y \u0111\u1ebfn v\u1ecb tr\u00ed ch\u1edbp nh\u00e1y tr\u00ean b\u1ea3n \u0111\u1ed3 \u0111\u1ec3 l\u00e0m nhi\u1ec7m v\u1ee5";
                cq = "D\u00e0nh cho Tr\u00e1i \u0110\u1ea5t\n";
                cr = "D\u00e0nh cho Nam\u1ebfc\n";
                cs = "D\u00e0nh cho Xayda\n";
                ct = "S\u1ee9c m\u1ea1nh y\u00eau c\u1ea7u";
                cu = "S\u1ee9c m\u1ea1nh c\u1ee7a b\u1ea1n";
                cv = "\u0110\u00e3 d\u00f9ng";
                cw = "\u00f4";
                cx = "N\u00e2ng c\u1ea5p";
                cy = "\u0110ang n\u00e2ng c\u1ea5p";
                cz = "G\u00e1n \u00f4\nph\u00edm t\u1eaft";
                cA = "V\u00e0o \u00f4\nth\u1ee9 ";
                cB = "C\u1ea5t v\u00e0o\nr\u01b0\u01a1ng";
                cC = "C\u1ea5t v\u00e0o r\u01b0\u01a1ng";
                cD = "N\u00f3i chuy\u1ec7n";
                cE = "H\u1ee5t";
                cF = "Cho";
                cG = "Nh\u1eadn";
                cH = "Nh\u1ea5n 2 l\u1ea7n";
                cI = "C\u00f3 th\u1ec3 thu ho\u1ea1ch";
                cJ = "Nh\u1ea5n Y \u0111\u1ec3 \u0111\u1ed3ng \u00fd (";
                cK = "Nh\u1ea5n # \u0111\u1ec3 \u0111\u1ed3ng \u00fd (";
                cL = "Xin kh\u1edfi \u0111\u1ed9ng l\u1ea1i game \u0111\u1ec3 c\u1eadp nh\u1eadt d\u1eef li\u1ec7u";
                cM = "\u0110ang online";
                cN = "\u0110ang offline";
                cO = "K\u1ebft b\u1ea1n";
                cP = "Chat player";
                cQ = "Chat v\u1edbi";
                cR = "Capsule cho bang";
                cS = "Capsule c\u00e1 nh\u00e2n";
                cT = "Capsule bang";
                cU = "Cho \u0111\u1eadu";
                cV = "Nh\u1eadn \u0111\u1eadu";
                cW = "Xin \u0111\u1eadu";
                cX = " l\u1ea7n";
                cY = "\u0110\u00e3 nh\u1eadn";
                cZ = "S\u1ee9c m\u1ea1nh";
                da = "Ng\u00e0y gia nh\u1eadp";
                db = "Bang ch\u1ee7";
                dc = "Ph\u00f3 bang";
                dd = "\u0110i\u1ec3m s\u1ee9c m\u1ea1nh";
                de = "Th\u00e0nh vi\u00ean";
                df = new String[]{"Th\u00e0nh", "vi\u00ean"};
                dg = new String[]{"Chat", "bang"};
                dh = new String[]{"R\u1eddi", "bang"};
                di = new String[]{"L\u1eadp", "bang"};
                dj = new String[]{"T\u00ecm", "bang"};
                dk = new String[]{"Kh\u1ea9u", "hi\u1ec7u"};
                dl = new String[]{"Bi\u1ec3u", "t\u01b0\u1ee3ng"};
                dm = new String[]{"Xin", "\u0111\u1eadu"};
                dn = "C\u1ea5p";
                do = "Ng\u00e0y th\u00e0nh l\u1eadp: ";
                dp = "Danh s\u00e1ch bang";
                dq = "Ch\u01b0a v\u00e0o bang";
                dr = new String[]{"Hi\u1ec7n t\u1ea1i bang ch\u1ec9 c\u00f3", " 1 th\u00e0nh vi\u00ean l\u00e0 b\u1ea1n.", " Xin ch\u1edd c\u00f3 ng\u01b0\u1eddi xin v\u00e0o.", " B\u1ea1n c\u00f3 th\u1ec3 ch\u1ecdn v\u00e0o nh\u00e2n v\u1eadt", " kh\u00e1c \u0111\u1ec3 m\u1eddi h\u1ecd v\u00e0o bang"};
                ds = "Nh\u1eadp t\u00ean bang";
                dt = "T\u00ean bang";
                du = "Chat bang";
                dv = "Nh\u1eadp t\u00ean bang c\u1ea7n t\u1ea1o";
                dw = "Nh\u1eadp kh\u1ea9u hi\u1ec7u bang";
                dx = "B\u1ea1n c\u00f3 mu\u1ed1n xin v\u00e0o bang ";
                dy = "Ch\u1ecdn bi\u1ec3u t\u01b0\u1ee3ng bang";
                dz = "Xin v\u00e0o\nbang";
                dA = "Xem th\u00e0nh\nvi\u00ean";
                dB = "Phong\nph\u00f3 bang";
                dC = "Phong\nch\u1ee7 bang";
                dD = "C\u1eaft ch\u1ee9c";
                dE = "Lo\u1ea1i th\u00e0nh vi\u00ean";
                dF = "B\u1ea1n h\u00e3y nh\u1eadp t\u00ean bang";
                dG = "B\u1ea1n h\u00e3y nh\u1eadp kh\u1ea9u hi\u1ec7u bang";
                dH = "Kh\u00f4ng t\u00ecm th\u1ea5y bang";
                dI = "tr\u01b0\u1edbc";
                dJ = "\u0110ang t\u00ecm bang";
                dK = "Giao d\u1ecbch";
                dL = " ch\u01b0a kh\u00f3a giao d\u1ecbch";
                dM = "Ch\u01b0a kh\u00f3a giao d\u1ecbch";
                dN = " \u0111\u00e3 kh\u00f3a giao d\u1ecbch";
                dO = "\u0110\u00e3 kh\u00f3a giao d\u1ecbch";
                dP = "Kh\u00f3a giao d\u1ecbch";
                dQ = "Ch\u1edd \u0111\u1ed1i th\u1ee7 kh\u00f3a";
                dR = "Nh\u1ea5t n\u00fat 'Xong'";
                dS = "Xong";
                dT = "\u0110\u1ed1i ph\u01b0\u01a1ng";
                dU = "B\u1ea1n";
                dV = "Kh\u00f3a";
                dW = "S\u1ed1 ti\u1ec1n giao d\u1ecbch";
                dX = "L\u1ea5y ra";
                dY = "B\u1ecf ra";
                dZ = "Cho \u0111\u1ec7 t\u1eed";
                ea = "B\u00e1n";
                eb = "Nh\u1eadp s\u1ed1 ti\u1ec1n mu\u1ed1n giao d\u1ecbch";
                ec = "Nh\u1eadp s\u1ed1 ti\u1ec1n";
                ed = "Nh\u1eadp sai s\u1ed1 ti\u1ec1n, vui l\u00f2ng nh\u1eadp l\u1ea1i";
                ee = "B\u1ea1n kh\u00f4ng \u0111\u1ee7 ti\u1ec1n, vui l\u00f2ng nh\u1eadp l\u1ea1i";
                ef = "Nh\u1eadp s\u1ed1 l\u01b0\u1ee3ng mu\u1ed1n giao d\u1ecbch";
                eg = "Nh\u1eadp s\u1ed1 l\u01b0\u1ee3ng";
                eh = "Nh\u1eadp sai s\u1ed1 l\u01b0\u1ee3ng, vui l\u00f2ng nh\u1eadp l\u1ea1i";
                ei = "\u0110\u00e3 c\u00f3 v\u1eadt ph\u1ea9m n\u00e0y";
                ej = "Vui l\u00f2ng m\u1edf kh\u00f3a tr\u01b0\u1edbc khi s\u1eed d\u1ee5ng v\u1eadt ph\u1ea9m \u0111\u1ec3 giao d\u1ecbch";
                ek = "g\u1ed1c";
                el = "c\u1ea7n";
                em = "\u0110\u1ee7";
                en = "Mi\u1ec5n ph\u00ed";
                eo = "Ch\u1ecdn v\u1eadt ph\u1ea9m";
                ep = "B\u1ea5t k\u00ec";
                eq = "Xin ch\u00e0o!";
                er = "C\u1eadu mu\u1ed1n mua g\u00ec?";
                es = "Con mu\u1ed1n h\u1ecdc g\u00ec?";
                et = "B\u1ea1n c\u00f3 ch\u1eafc mu\u1ed1n giao d\u1ecbch v\u1edbi nh\u1eefng v\u1eadt ph\u1ea9m tr\u00ean kh\u00f4ng ?";
                eu = "H\u1ecdc v\u1edbi";
                ev = "Mua b\u1eb1ng";
                ew = "Kh\u00f4ng th\u1ec3 th\u1ef1c hi\u1ec7n khi \u0111ang ki\u1ec7t s\u1ee9c";
                ex = "S\u1eed d\u1ee5ng\n\u0111\u1ec3\nk\u1ebft h\u1ee3p";
                ey = "S\u1eed d\u1ee5ng\n\u0111\u1ec3\ngiao d\u1ecbch";
                ez = "B\u1ea1n kh\u00f4ng \u0111\u1ee7 ng\u1ecdc \u0111\u1ec3 chat k\u00eanh th\u1ebf gi\u1edbi";
                eA = "Chat k\u00eanh th\u1ebf gi\u1edbi (5 ng\u1ecdc)";
                eB = " mu\u1ed1n giao d\u1ecbch v\u1edbi b\u1ea1n, b\u1ea1n c\u00f3 \u0111\u1ed3ng \u00fd kh\u00f4ng ?";
                eC = "B\u1ea1n v\u1eeba n\u00e2ng c\u1ea5p ";
                eD = " sang c\u1ea5p ";
                eE = "ti\u1ec1m n\u0103ng \u0111\u1ebfn S\u01b0 ph\u1ee5 \u0111\u1ec3 h\u1ecdc";
                eF = "\u0110i\u1ec3m ti\u1ec1m n\u0103ng";
                eG = "\u0110i\u1ec3m th\u00e0nh t\u00edch";
                eH = "t\u0103ng";
                eI = "T\u0103ng";
                eJ = "B\u1ea1n ch\u1ec9 c\u00f3 ";
                eK = " \u0111i\u1ec3m ti\u1ec1m n\u0103ng. H\u00e3y luy\u1ec7n t\u1eadp th\u00eam \u0111\u1ec3 c\u00f3 \u0111\u1ee7 ";
                eL = "B\u1ea1n c\u00f3 mu\u1ed1n d\u00f9ng ";
                eM = " ti\u1ec1m n\u0103ng \u0111\u1ec3 t\u0103ng v\u00e0o ";
                eN = " HP kh\u00f4ng?";
                eO = " KI kh\u00f4ng?";
                eP = " s\u1ee9c \u0111\u00e1nh kh\u00f4ng?";
                eQ = " ch\u00ed m\u1ea1ng kh\u00f4ng?";
                eR = "Khi c\u00f3 ";
                eS = " ti\u1ec1m n\u0103ng, b\u1ea1n s\u1ebd \u0111\u01b0\u1ee3c n\u00e2ng c\u1ea5p mi\u1ec5n ph\u00ed ";
                eT = ". Ngo\u00e0i ra b\u1ea1n c\u00f3 th\u1ec3 mua B\u00ed K\u00edp t\u1eeb Ur\u00f4n \u0111\u1ec3 h\u1ecdc nhanh";
                eU = "HP";
                eV = "KI";
                eW = "S\u1ee9c \u0111\u00e1nh";
                eX = "Gi\u00e1p";
                eY = "Th\u1ec3 l\u1ef1c";
                eZ = "Ch\u00ed m\u1ea1ng";
                fa = "C\u1ea5p \u0111\u1ed9";
                fb = "KI ti\u00eau hao: ";
                fc = "H\u1ed3i chi\u00eau";
                fd = "\u0110\u00e3 \u0111\u1ea1t c\u1ea5p t\u1ed1i \u0111a";
                fe = "C\u1ea5p k\u1ebf c\u1ea7n ";
                ff = "ti\u1ec1m n\u0103ng";
                fg = "Ch\u01b0a h\u1ecdc";
                fh = "\u0110\u1ec3 h\u1ecdc c\u1ea7n ";
                fi = "H\u1ecdc";
                fj = "\u0111\u1ec3 t\u0103ng 20 HP g\u1ed1c";
                fk = "\u0111\u1ec3 t\u0103ng 20 MP g\u1ed1c";
                fl = "\u0111\u1ec3 t\u0103ng 1 s\u1ee9c m\u1ea1nh g\u1ed1c";
                fm = new String[][]{{"Gohan", "Krillin", "Yamcha"}, {"\u1ed0c ti\u00eau", "Pocollo", "Kami"}, {"Ca\u0111ic", "Ra\u0111ic", "Kakalot"}};
                if (l.c == 7) {
                    fm = new String[][]{{"Hango", "Linkhi", "Chayam"}, {"Deden", "Cololo", "Mika"}, {"Tageve", "Ditra", "Rotkaka"}};
                }
                fn = "\u0110\u1ecba \u0111i\u1ec3m nhi\u1ec7m v\u1ee5";
                fo = "Kh\u00f4ng c\u00f3 nhi\u1ec7m v\u1ee5";
                fp = "Ho\u00e0n th\u00e0nh, th\u01b0\u1edfng ";
                fq = "Nhi\u1ec7m v\u1ee5 th\u00e0nh t\u00edch";
                fr = "Trang b\u1ecb";
                fs = "B\u1ea1n mu\u1ed1n l\u00e0m g\u00ec";
                fv = "Ch\u1ecdn n\u01a1i mu\u1ed1n \u0111\u1ebfn";
                ft = "Ch\u1ecdn";
                fu = "Ch\u1ecdn";
                fw = "Ch\u1ecdn \u0111\u1ec3 \u1ea9n chat th\u1ebf gi\u1edbi";
                fx = "Ch\u1ecdn \u0111\u1ec3 hi\u1ec7n chat th\u1ebf gi\u1edbi";
                ge = "Ch\u01a1i m\u1edbi";
                gf = "Ch\u01a1i TK";
                gh = "Ch\u01b0a \u0111\u0103ng k\u00fd";
                gl = "ti\u1ec1m n\u0103ng \u0111\u1ebfn Whis \u0111\u1ec3 h\u1ecdc";
                return;
            }
            case 1: {
                bs.l = "http://world.teamobi.com";
                bs.l = "";
                x.j = l.b("/mainImage/logo1E.png");
                a = "Go to Whis (Beerus Planet) to learn skill";
                b = "When reach maximum proficiency, go to Whis (Beerus Planet) to upgrade skill";
                c = "Proficiency";
                d = "Delete account";
                e = "You bought many gems today. Let's try again tomorrow!";
                f = "When selling successfully, you will receive Ruby non Gem. Do you want to continue consign?";
                g = "Equip";
                h = "Unlock";
                i = "Collection book";
                j = "Not enough";
                k = "Function in maintenance.";
                az = "Are you sure you want to pick this item ?";
                l = "level";
                m = "Results lucky number";
                bS = "Who to choose";
                bR = "Notification";
                n = "Auto reborn";
                o = "Auto function";
                p = "Are you sure you fusion forever with your disciple? You will lost your disciple and all disciple's equip, all disciple's power will convert to your potential.";
                gj = "Fusion dance forever";
                gi = "Fusion dance";
                gg = "Please, enter the valid quantity";
                q = "Continue";
                v = "Go home";
                u = "Status";
                r = "Attack";
                s = "Protect";
                t = "Follow";
                w = "Disciple";
                gk = "Go to";
                x = "Connection lost. Please try again later";
                y = "Low graphics";
                z = "High graphics";
                gb = "Download";
                gc = "Clear data";
                gd = "When game have data errors, you should delete data. After delete data, you have to download data to play game.";
                ga = "Cancel";
                fZ = "Please download data to play";
                A = "Abracadabra...";
                D = "Congratulations my dear";
                B = "Better luck next time my dear";
                fY = "Do you want go to future now with 1 gem ?";
                fX = "Speed up";
                E = "Analog";
                F = "Analog";
                G = "Analog";
                fU = "Inventory Password ";
                fV = "Enter Security password";
                fW = "Security password must be 6 number.";
                fT = "Please enter your number phone or email ,then enter your password to create new account";
                fS = "You will lost your account forever if you change to another account,do you agree ?";
                H = "Register to protect account";
                fR = "You must finish the mission find 6 star dragon ball to recharge";
                fQ = "Forum and Buy more gems";
                C = "Buy more gems";
                fP = "No items to buy";
                fO = "Hold up to get more";
                fN = "Hold down to get more";
                fM = "Page";
                fL = "Up top";
                fD = "Consign by\ngold";
                fE = "Consign by\ngem";
                fF = "Consign by gold";
                fG = "Consign by gem";
                fH = "Cancel\nconsign";
                fI = "Get\nmoney";
                fK = "Sold";
                fJ = "Selling";
                fC = "Consign";
                fz = "Sound";
                fA = "Sound";
                fB = "No enemy";
                aa = "Select server";
                bK = "Rank";
                bL = "Active point";
                I = "Registering";
                J = "Sent message, please wait for confirmed message.";
                K = "Message can not be delivered. Please check your account and restart game.";
                dZ = "User for\ndisciple";
                L = "Message delivered";
                M = "Can not send message";
                N = "Congratulation, you have just send predicted message successfully.";
                O = "Message sending failed.";
                P = "Password must be 6 characters length.";
                Q = "Enter number for private password only.";
                R = "Enter private password";
                S = "Select account";
                T = "You didn't enter you email or phone number.";
                U = "You didn't enter password";
                V = "Account name must be longer than 5 character";
                W = "Phone number is invalid. Please enter like these following form: 0912345678 or 84918765432";
                X = "Email is invalid. Please enter like these following form: yournamehere@yahoo.com or yournamehere@gmail.com";
                Y = "Register\nnew\naccount";
                Z = "Select\nserver";
                ab = "Forget pwd";
                ac = "Password";
                String[] stringArray = new String[]{"Didn't have account? Please", "choose register menu."};
                ad = "Message";
                ae = new String[]{"Message", ""};
                af = "No message";
                ag = "Do you want to cancel account protection function ?";
                ah = "Please check your account information carefully to recover account, in case forgot password\n";
                ai = "Phone number";
                aj = "Email";
                ak = "Acc";
                al = "Pwd";
                am = "To recover password, please visit website http://ngocrongonline.com/matkhau";
                an = "Dragon Ball";
                ao = "Character";
                ap = "Account";
                aq = "Account server";
                ar = "You didn't enter character name";
                as = "Character name can not too short";
                at = "Character name can not longer than 15 characters";
                au = "Character need to change name";
                av = "Character name";
                aw = "Log in";
                ax = "Log in";
                ay = "Register";
                bq = "Revenge";
                aA = "Wait";
                aB = "Please wait";
                aC = "Connecting";
                aD = "Downloading ";
                aE = "Error! please restart game.";
                aF = "Change zone";
                aG = "Select zone";
                aH = "Website\nforum";
                aI = "Server";
                String[] stringArray4 = new String[]{"Inventory", "Skill", "Potential", "Info", "Equipment"};
                aJ = new String[]{"", "People: ", "Hair: "};
                aK = new String[]{"Earth", "Namekian", "Saiyan"};
                if (l.c == 7) {
                    aK = new String[]{"Earth dragon", "Green dragon", "Red dragon"};
                }
                aL = new String[]{"Challenge", "Practice", "PK", "Add friend", "Invite clan", "Recover", "Information", "Private chat", "Invite to clan", "Block invite to clan"};
                aM = new String[][]{{"Quest", ""}, {"Inven-", "tory"}, {"Skill", ""}, {"Func-", "tion"}};
                aN = new String[][]{{"Quest", ""}, {"Inven-", "tory"}, {"Skill", ""}, {"Clan", ""}, {"Func-", "tion"}};
                aO = new String[][]{{"Dis-", "ciple"}, {"Status", ""}, {"Inven-", "tory"}};
                aP = new String[][]{{"Dis-", "ciple"}, {"Status", ""}};
                aQ = new String[]{"Add\nkey Q", "Add\nkey W", "Add\nkey E", "", "", "", "", ""};
                aR = new String[]{"Add\nkey 7", "Add\nkey 8", "Add\nkey 9", "", "", "", "", ""};
                aS = "Your current attack skill didn't add points";
                aT = "Out of Senzu Bean. Come back and harvest more";
                aU = "You are already in this zone";
                aV = new String[]{"Find ", " at ", " to receive quest.", "You now complete all quests of this version, please wait for upcoming version."};
                aW = new String[]{"Exhausted", "Wait", "Return home", "Revive\nnow\n(1 gem)"};
                String[] stringArray5 = new String[]{"Map", "Quest", "Clan"};
                aX = new String[]{"Senzu Bean is used for recovering HP and KI immediately", "You can only keep 10 Senzu Beans belong with you. If you want to have more, ask from your clan's friend", "All skills can be learnt free at Kame-Sennin, when you have enough potential points", "You can not fly or use skill if out of KI", "Attack monsters with your clan's friend will bring more potential points than training alone", "Training with your friends at appropriate zone will brought more potential points than attack monsters", "When upgraded, Senzu Bean will recover more HP and KI", "Login daily to get free Gem", "Chicken drumsticks will recover 100% HP and KI. Tomato recover 100% KI. Carrot recover 100% HP", "Senzu Bean tree will ripe after a period, even though you are offline", "If you don't login in 3 days, you power will decrease because of your laziness", "Your strength will decrease when attack monster, but it will increase when you stop", "Out of Gem? Go find NPC Bora"};
                aY = "After join class, you can receive quest from Head Master";
                aZ = "Serial number";
                ba = "Card's code";
                bb = "Pay Vina ,Mobi, Viettel, VTC";
                bc = "Pay card";
                bd = "Please enter serial number";
                be = "Please enter card's code";
                bf = "bil";
                bg = "mil";
                bh = "Menu";
                bi = "Close";
                bj = "Clear";
                bk = "Continue";
                bl = "Use";
                bm = "Yes";
                bn = "No";
                bo = "Exit";
                bp = "Chat";
                br = "OK";
                bs = "Remember";
                bt = "Accept";
                bu = "Cancel";
                bv = "Select";
                bw = "Enter";
                bx = "Open link";
                aw.by = "New character";
                bz = "Back";
                bA = "Kill";
                bB = "Kill boss";
                bC = "gold";
                bD = "gem";
                bE = "ruby";
                bF = "You PK point is ";
                bG = " attacks you";
                bH = "Not enough KI to use";
                bI = "You have received";
                bJ = "You have learnt ";
                bM = "Friend";
                bN = "Enemy";
                bO = "No friend";
                bP = "World chat";
                bQ = "Change flag";
                bT = "Option";
                bU = "Increase resolution (strong devices)";
                bV = "Decrease resolution (weak devices)";
                bW = "Server notice";
                ca = "Special aura";
                cb = "Power aura";
                bY = "Small screen";
                bX = "Big screen";
                bZ = "Do you want to exit game to change screen size?";
                cc = "Chest";
                cd = new String[]{"Chest", ""};
                ce = new String[]{"Inven-", "tory"};
                cf = new String[]{"Combine", ""};
                cg = new String[]{"Map", ""};
                ch = new String[]{"Give", "item"};
                ci = new String[]{"Receive", "item"};
                cj = new String[]{"Zone", ""};
                ck = "Zone";
                cl = "Map";
                cm = "Receive item";
                cn = "Receive";
                co = "Receive All";
                cp = "Go to the flashing point on the map for quest";
                cq = "For Earth only\n";
                cr = "For Namekian Only\n";
                cs = "For Xaiyan Only\n";
                ct = "Power required";
                cu = "Your power";
                cv = "Used";
                cw = "place";
                cx = "Upgrade";
                cy = "Upgrading";
                cz = "Add\nShort cut";
                cA = "Into\nplace ";
                cB = "Move to\nchest";
                cC = "Move to\nchest";
                cD = "Chat";
                cE = "Miss";
                cF = "Donate";
                cG = "Receive";
                cH = "Double Tap";
                cI = "Can harvest";
                cJ = "Press Y to accept (";
                cK = "Press # to accept (";
                cL = "Please restart game to update data";
                cM = "Online";
                cN = "Offline";
                cO = "Make friend";
                cP = "Chat player";
                cQ = "Chat with";
                cR = "Capsule Donate";
                cS = "Personal Capsule";
                cT = "Clan's Capsule";
                cU = "Give bean";
                cV = "Receive bean";
                cW = "Request bean";
                cX = " time";
                cY = "Received";
                cZ = "Power";
                da = "Join date";
                db = "Clan Leader";
                dc = "Clan coleader";
                dd = "Power points";
                de = "Member";
                df = new String[]{"Member", ""};
                dg = new String[]{"Chat", "clan"};
                dh = new String[]{"Leave", "clan"};
                di = new String[]{"Create", "clan"};
                dj = new String[]{"Find", "clan"};
                dk = new String[]{"Slogan"};
                dl = new String[]{"Icon"};
                dm = new String[]{"Request", "bean"};
                dn = "Level";
                do = "Clan birthday";
                dp = "Clan list";
                dq = "Not joint clan";
                dr = new String[]{"You are the only one", " member of this clan.", " Someone may request to join.", " You can select other players", " to invite them join clan"};
                ds = "Enter clan's name";
                dt = "Clan's name";
                du = "Clan chat";
                dv = "Enter clan's name you want to create";
                dw = "Enter clan's slogan";
                dx = "Do you want to join clan ";
                dy = "Select clan's icon";
                dz = "Request join\nclan";
                dA = "View clan's\nmember";
                dB = "Order\ncoleader";
                dC = "Order\nleader";
                dD = "Dismiss";
                dE = "Kick member";
                dF = "Please enter clan's name";
                dG = "Please enter clan's slogan";
                dH = "Can not find clan";
                dI = "ago";
                dJ = "Finding clan";
                dK = "Trade";
                dL = " didn't lock transaction";
                dM = "Transaction is not locked";
                dN = " locked transaction";
                dO = "Transaction is locked";
                dP = "Lock transaction";
                dQ = "Wait opponent to lock transaction";
                dR = "Press 'Done'";
                dS = "Done";
                dT = "Opponent";
                dU = "You";
                dV = "Lock";
                dW = "Transaction amount";
                dX = "Move to Equipment";
                dY = "Remove";
                ea = "Sale";
                eb = "Enter money to trade";
                ec = "Enter money";
                ed = "Enter wrong amount, please try again";
                ee = "Not enough money, please try again";
                ef = "Enter quantity you want to trade";
                eg = "Enter quantity";
                eh = "Enter wrong quantity, please try again";
                ei = "You already have this item";
                ej = "Please unlock before trade this item";
                ek = "Base";
                el = "need";
                em = "Need";
                en = "Free";
                eo = "Select item";
                ep = "Random";
                eq = "Hello!";
                er = "What do you want to buy?";
                es = "What do you want to lear?";
                et = "Are you sure you want to trade with those items?";
                eu = "Learn with";
                ev = "Buy with";
                ew = "You can not perform this action when dying";
                ex = "Use\nfor\ncombine";
                ey = "Use\nfor\ntrade";
                ez = "You don't have enough gem to chat on world channel";
                eA = "Chat on world channel (5 gems)";
                eB = " want to trade with you, do you accept?";
                eC = "You have just upgrade ";
                eD = " to ";
                eE = "potential to Master to learn";
                eF = "Potential points";
                eG = "Achievement point";
                eH = "increase";
                eI = "Increase";
                eJ = "You only have ";
                eK = " potential pts. Let's practice more to earn ";
                eL = "Do you want to use ";
                eM = " potential pts to add ";
                eN = " for HP?";
                eO = " for KI?";
                eP = " for attack?";
                eQ = " for critical?";
                eR = "At ";
                eS = " potential points, you can upgrade for free ";
                eT = ". Or see Uron to buy recipes faster.";
                eU = "HP";
                eV = "KI";
                eW = "Attack";
                eX = "Armor";
                eY = "Vitality";
                eZ = "Critical";
                fa = "Level";
                fb = "KI consume: ";
                fc = "Cooldown";
                fd = "Maximum level reached";
                fe = "Next level required ";
                ff = "potential";
                fg = "Not learnt";
                fh = "Require ";
                fi = "Learn";
                fj = "to gain 20 HP";
                fk = "to gain 20 MP";
                fl = "to gain 1 power point";
                fm = new String[][]{{"Gohan", "Krillin", "Yamcha"}, {"Dende", "Piccolo", "Kami"}, {"Vegeta", "Raditz", "Kakarot"}};
                if (l.c == 7) {
                    fm = new String[][]{{"Hango", "Linkhi", "Chayam"}, {"Deden", "Cololo", "Mika"}, {"Tageve", "Ditra", "Rotkaka"}};
                }
                fn = "Quest place";
                fo = "You don't have quest";
                fp = "Complete, reward ";
                fq = "Achievement quest";
                fr = "Equipment";
                fs = "What do you want to do";
                ft = "Select";
                fu = "Select";
                fv = "Select your destination";
                fw = "OK to disable World Channe";
                fx = "OK to enable world channel";
                ge = "New game";
                gf = "Play acc";
                gh = "Not register yet";
                gl = "potential to Whis to learn";
                return;
            }
            case 2: {
                bs.l = "http://dragonball.indonaga.com";
                x.j = l.b("/mainImage/logo1E.png");
                bz.a();
            }
        }
    }
}
